[package]
name = 'token_bridge_contract'
type = 'contract'

[dependencies]
aztec = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.16.9', directory = 'yarn-project/aztec-nr/aztec' }
protocol_types = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.16.9', directory = 'yarn-project/noir-protocol-circuits/src/crates/types' }
token_portal_content_hash_lib = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.16.9', directory = 'yarn-project/noir-contracts/src/contracts/token_portal_content_hash_lib' }
